
export const SET_COMPLETED_LAUNCHES_LIST = 'SET_COMPLETED_LAUNCHES_LIST';
export const SET_FILTERED_COMPLETED_LAUNCHES_LIST = 'SET_FILTERED_COMPLETED_LAUNCHES_LIST';
export const SET_UPCOMING_LAUNCHES_LIST = 'SET_UPCOMING_LAUNCHES_LIST';
export const SET_FILTERED_UPCOMING_LAUNCHES_LIST = 'SET_FILTERED_UPCOMING_LAUNCHES_LIST';

export const HANDLE_FILTER_MODAL = 'HANDLE_FILTER_MODAL';
export const HANDLE_FILTER_START_DATE = 'HANDLE_FILTER_START_DATE';
export const HANDLE_FILTER_END_DATE = 'HANDLE_FILTER_END_DATE';