 export const HOME_SCREEN = {
    UP_COMING_LAUNCHES : 'UP COMING',
    UP_COMING_LAUNCHES_PAGE : 'UP_COMING_LAUNCHES_PAGE',
    COMPLETE_LAUNCHES : 'COMPLETE',
    COMPLETED_COMING_LAUNCHES_PAGE : 'COMPLETED_COMING_LAUNCHES_PAGE',
    DETAILS_PAGE : 'DETAILS_PAGE'
  };
  